name: Build Main

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 20 1 * *'

jobs:
  build_and_test:
    name: "Build and Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
        
      - name: Archive jars
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: build/libs
          
      - name: Archive reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: build/reports
