name: Build Branches

on:
  push:
    branches-ignore:
      - main

jobs:
  build_and_test:
    name: "Build and Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
        
      - name: Archive jars
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: build/libs
          
      - name: Archive reports
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: build/reports
                
  owasp_check:
    name: "OWASP Check"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Cache Depdendency-Check-Data
        uses: actions/cache@v3
        with:
          path: ~/.gradle/dependency-check-data
          key: ${{ runner.os }}-gradle-dependency-check-data-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew dependencyCheckAnalyze

  graal_vm_images:
    runs-on: ubuntu-latest
    needs: [build_and_test, owasp_check]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew nativeImage --info
        
      - name: Archive native image
        uses: actions/upload-artifact@v3
        with:
          name: nokia3310-ubuntu-latest
          path: ./build/graal/nokia3310contacts
